services:
  - type: web
    name: enterprise-rag-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: COLLECTION_NAME
        value: compliance_documents
      - key: ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /api/v1/health
